In [18]:
import pandas as pd
import numpy as np

In [19]:
# read excel 1. Give full path if not in the same folder. 
# Specify sheetname 
df_excel = pd.read_excel('/Users/malik/PythonProjects/Leads to CRM.xlsx', "Tag Report")
df_excel.head()

,Date-Time,Date,Time,Contact ID,Country,Primary List,Contact Country,Email,Original Tag Name,First Name,Last Name,Tag Name (For Reports),Campaign Name (For Reports),Source URL,Company
0,2021-01-12T02:29:44-06:00,12-01-2022,08:29 AM UTC,10953,BG_BG,bg/bg,NaN,omega.invest.ood@gmail.com,E-mail double opt-in ok,Nikolai,Kolev,E-mail double opt-in ok,Double Opt In,https://cloud.also.mp/bg/bg/microsoft-365-clou...,NaN
1,2021-01-13T14:13:51-06:00,13-01-2022,08:13 PM UTC,10969,BG_BG,bg/bg,NaN,tatyanazakaryan@gmail.com,E-mail double opt-in ok,Татяна,Закарян,E-mail double opt-in ok,Double Opt In,https://cloud.also.mp/bg/bg/microsoft-365-clou...,NaN
2,2021-01-11T11:01:20-06:00,11-01-2022,05:01 PM UTC,10901,BG_BG,bg/bg,NaN,nikolaymarinovm@abv.bg,M365CA: 01 Signed Up,Николай,Маринов Маринов,01 Signed Up,M365 Cloud Awareness (New Countries),https://cloud.also.mp/bg/bg/microsoft-365-clou...,NaN
3,2021-01-11T12:14:25-06:00,11-01-2022,06:14 PM UTC,10943,BG_BG,bg/bg,NaN,blashko888@gmail.com,M365CA: 01 Signed Up,Blagovest,Jivkov Avramov,01 Signed Up,M365 Cloud Awareness (New Countries),https://cloud.also.mp/bg/bg/microsoft-365-clou...,NaN
4,2021-01-11T20:20:22-06:00,11-01-2022,02:20 AM UTC,10950,BG_BG,bg/bg,NaN,entity.ins@gmail.com,M365CA: 01 Signed Up,Теодора,Любомирова Спасова,01 Signed Up,M365 Cloud Awareness (New Countries),https://cloud.also.mp/bg/bg/microsoft-365-clou...,NaN

In [20]:
# read the excel 2. Give full path if not in the same folder. 
# Specify sheetname 
df_activecampaign = pd.read_csv('/Users/malik/PythonProjects/all contacts.csv', low_memory=False)

#get all column names first

list(df_activecampaign.columns)

['ID',
 'Email',
 'First Name',
 'Last Name',
 'Phone Number',
 'Date Created',
 'IP Address',
 'User Agent',
 'Organization',
 'Account (previously Organization)',
 'Account ID',
 'Job Title',
 '*Training 104 ACMP Voucher Code - MIC-CUS-A-E-211210-2',
 '*Organisation Name',
 '*Training 105 ACMP Voucher Code - MIC-AZ140-E-211213-1',
 '*Source',
 '*Training 106 ACMP Voucher Code - MIC-AZ140-E-211213-2',
 '*Lead ID',
 '*Training 107 ACMP Voucher Code - MIC-SC400-E-211213',
 '*Title',
 '*Training 108 ACMP Voucher Code - MIC-CUS-A-E-211217',
 '*IT Company',
 '*Training 109 ACMP Voucher Code - MIC-SC200-E-211220',
 '*IBM - Product Interest',
 '*State',
 '*Consent to share data with Neural Impact',
 '*Proposed company',
 '*Sign Now Service Requested',
 '*Ques EXO I: Data Assess Score',
 '*Teams Essentials Requests',
 '*Ques EXO I: Info Assess Score',
 '*Teams Essentials Reason For Contacting',
 '*Ques EXO I: Teamwork Assess Score',
 '*Teams Essentials Reseller Requests',
 '*Ques EXO I: Cost Assess Score',
 '*Teams Essentials Reseller Reason For Contacting',
 '*Ques MSBT: Do you offer any subscription type, usage- or consumption-based (cloud) services?',
 '*Hostpool Reason for Callback',
 '*Hostpool Requested Callback',
 '*Desired Start Date Bizapps High Potential',
 '*Ques MSBT: Do you have a focus on specific customer industry or vertical?',
 '*Plant a Tree - Which devices are you selling?',
 '*Ques MSBT: Do you have a unique offering that differentiates your company on the market?',
 '*Plant A Tree Requested Call back',
 '*Plant A Tree Reason for call back',
 '*Ques MSBT: Do you have compensation or bonus program for sales people?',
 '*Referee First Name',
 '*Ques MSBT: How you evaluate your company’s marketing capabilities?',
 '*Referee Last Name',
 '*Referee Company',
 '*Referee Phone Number',
 '*Referee Email',
 '*Ques MSBT: What are the most important business topics you would like to learn about?',
 '*Worked with ACMP',
 '*Ques MSBT: How many customers are you serving on regular basis?',
 '*ALSO Services Reseller Webinars Feb2022',
 '*Ques MSBT: Do you offer own service or IP (such as repeatable processes, workflows etc.)?',
 '*Modern Marketing Academy Promo Code',
 '*Ques MSBT: Do you use ALSO Cloud Marketplace management platform today?',
 '*PL End Customer Guide or Callback',
 '*Ques MSBT: Do you cooperate with other players on the market if your expertise is limited?',
 '* Already Using Microsoft',
 '*Ques MSBT: Please rate how much of your customers ask for your advise on IT related topics',
 '*i would like to register to',
 '*Ques MSBT: How do you manage and keep your existing customers?',
 '*W365 Customer I Would Like To',
 '*Ques MSBT: Are you current ALSO customer?',
 '*W365 Reseller Would Like to',
 '*Ques MSBT: Would you like to be contacted by Local ALSO representative?',
 '*MS Defender Business Webinar',
 '*Country',
 '*MS Defender Business Contact Reason',
 '*MS Defender Business Reason Other',
 '*ADP_Part_1_Link',
 '*Selected Webinars for ADP',
 '*Defender Promo Contract ID',
 '*ADP_Part_2_Link',
 '*3 step bizapps program choice 2022',
 '*ADP_Part_3_Link',
 '*bamboom_cloud_webinar_2022',
 '*ADP_Part_4_Link',
 '*Teams Essentials Request Rally PC',
 '*Reason for call back Rally PC',
 '*MS Defender Standalone Comment',
 '*Message from customer',
 '*MS Cloud Partner Program Chosen Options',
 '*Interests',
 '*Consultation with Hortus',
 '*Contact Type',
 '*AzureSecurityWebinars',
 '*Allergies',
 '*mature_acmp_choice',
 '*Source URL',
 '*emerging_acmp_choice',
 '*Ques EXO I: Data Security Assessment Responses',
 '*ACMP Partner Sales',
 '*No of Employees',
 '*ACMP Partner Sales Email 2',
 '*Topics Interested',
 '*ACMP Partner Sales Email 3',
 '*Ques AHUB: Company Type',
 '*WaaS Campaign Selected Options',
 '*Ques AHUB: Azure Implementations Done',
 '*ACMP WaaS Comments',
 '*Ques AHUB: Azure Services Offered',
 '*Readynez Training 6XX Name',
 '*Ques AHUB: What are you missing?',
 '*Readynez Training 6XX Link',
 "*Ques AHUB: Interested in ALSO's Proof of Concept",
 '*Readynez Training 6XX Date',
 '*AHUB Live Webinar Join URL',
 '*Security Campaign Choice',
 '*Customers Needs',
 '*security campaign reason for meeting request',
 '*Business Details',
 '*Bg rrf funds webinar product interest',
 '*Bg rrf funds webinar information interest',
 '*Marketing Channel',
 '*Company Size',
 '*StorageCraft GoToWebinar Join URL',
 '*Bg rrf funds webinar form selections',
 '*Ques M365: Need further information on M365 Business',
 '*City',
 '*Industry',
 '*Do you have Preferred IT-Partner?',
 '*Name of Preferred IT Partner',
 '*Does your company have a Microsoft tenant?',
 "*Ques AHUB: Would you like the ALSO sales team to get in touch with you to discuss Microsoft Azure's suitability for your organisation?",
 '*Ques TeamsTrial Partner: Avg Customer Size.',
 '*Ques TeamsTrial Partner: Are you experienced with selling either Office 365 or Microsoft 365?',
 '*Are you Experienced in Selling Project Or Visio?',
 '*Do you want to receive Marketing Materials for Project & Visio?',
 '*Project & Visio Webinar Join URL',
 '*Do you want the M365 Business 20 offer? Can we contact you with your individual offer?',
 '*E1 Plus Dropsuite Webinar Join URL',
 '*Device',
 '*Office Software',
 '*Kommunikation',
 '*Security',
 '*Rental Period',
 '*Postcode',
 '*Requested Call Back',
 '*Are you experienced with selling Office 365?',
 '*Agreed to contact?',
 '*ACMP Contract ID',
 '*Airslate SignNow Webinar Join URL',
 '*Interested In Future Readiness Trainings',
 '*Which of the following do your customers ask you about?',
 '*Are you also interested in learning about Dynamics 365 Sales Professional? ',
 '*Dyn365 Sales Professional - Desired support plan',
 '*Are you also interested in learning about Dynamics 365 Business Central?',
 '*BizApps Office Hours Webinars Registrations',
 '*Dynamics 365 Business Central Meeting Time Scheduled',
 '*Dynamics 365 Sales Professional Meeting Time Scheduled',
 '*Dropbox First Launch GTW Webinar URL',
 '*MWP Trainings',
 '*MWP Training 17 Aug Join URL',
 '*MWP Training 18 Aug Join URL',
 '*MWP Training 19 Aug Join URL',
 '*MWP Training 20 Aug Join URL',
 '*MWP Training 21 Aug Join URL',
 '*MWP Registrations - 17 Aug',
 '*MWP Registrations - 18 Aug',
 '*MWP Registrations - 19 Aug',
 '*MWP Registrations - 20 Aug',
 '*MWP Registrations - 21 Aug',
 '*BizApps Training Series',
 '*Already Using Microsoft 365',
 '*Do you have experience selling Microsoft 365',
 '*Azure Training 2020 10 Jens',
 '*Project Visio Trainings Sep 2020',
 '*Reason for Call Back',
 '*Are you already registered in the ALSO Cloud Marketplace?',
 '*Interested in following GTM Support Programs',
 '*Interested in GTM Support Programs for Following Solutions',
 '*Want More Information on ALSO Opportunity Program?',
 '*Want to apply for ALSO Oppprtunity Program and is Aware of Costs?',
 '*Experience With Azure',
 '*CEE MC EMPM Azure BG Partner Trainings',
 '*CEE MC EMPM MWP Partner Trainings',
 '*MWP Training Series Q2',
 '*I want to receive more details on the Support packages.',
 '*Already Use Business Applications',
 '*P & V Webinar - 01 Dec Join Link',
 '*P & V Webinar - 09 Dec Join Link',
 '*P & V Webinar - 15 Dec Join Link',
 '*Do you already use Office 365 or Microsoft 365 in your company?',
 '*I would like to be called by an ALSO representative and get a recommendation of an ALSO trusted IT-Partner.',
 '*Are you experienced in selling Microsoft Visio or Power Platform?',
 '*Send me the free ACMP one Pager',
 '*CSP Awareness Support Needed For',
 '*Microsoft FY21 KickOff Webinars',
 '*Azure Training 2021 FR',
 '*BizApps Trainings FR',
 '*WVD Promo Reason for contacting',
 '*3 Step Program Chosen',
 '*3 Step Program - Requested 1-on-1?',
 '*3 Step Program - 1-on-1 Date Suggestions',
 '*Tech Fundamental Trainings Signed Up For',
 '*Microsoft Certified Email',
 '*Microsoft Partner Network ID',
 '*Tech Fundamentals Trainings Promo Code',
 '*Consent to be contacted by ALSO',
 '*Consent to be contacted by Readynez',
 '*Consent for €99 Tech Fund Trainings Cancellation',
 '*Do you use Amazon Web Services?',
 '*What Challenges do you see in starting cloud business?',
 '*Which cloud scenarios you imagine for your company?',
 '*Visorian Webinars Registration',
 '*Requested WVD Demo Access',
 '*Cloud Day Baltic Trainings',
 '*Squalio ThP Latvia Webinars',
 '*Martins Internal BizApps Trainings',
 '*Would like to get access to',
 '*olp 2 csp webinar pl',
 '*New Azure Plans Reason For Contacting',
 '*WaaS Equipment',
 '*WaaS Office Software',
 '*WaaS Kommunikation',
 '*WaaS Security',
 '*WaaS Time Period',
 '*WaaS Miscellaneous',
 '*MS QS Security Interested In',
 '*ISV Workshops',
 '*Azure Plans and Transition Whitepaper',
 '*Inspire2021 Area of Interest',
 '*Inspire 2021 Reason for Contacting',
 '*Tax ID',
 '*Cancellation Policy Acknowledgement',
 '*Interested In ALSO Readiness Program',
 '*Readyness Projects Trainings',
 '*Data Sharing Consent',
 '*Cancellation Policy Acceptance',
 '*Readyness Training Codes with UUIDs',
 '*Reminder Email Webinar Name',
 '*Reminder Email Teams Link',
 '*Readiness Project Attended Webinar Name',
 '*Account Manager (Sales Email)',
 '*Readyness Project Trainings MWP',
 '*Readyness Project Trainings MWP Voucher Codes',
 '*Readyness Project Trainings MWP UUIDs',
 '*Training 19 ACMP Voucher Code - MIC-CUS-A-E-210906',
 '*Training 23 ACMP Voucher Code - MIC-CUS-A-E-210908',
 '*Training 26 ACMP Voucher Code - MIC-AZ140-E-210920',
 '*Training 27 ACMP Voucher Code - MIC-M365IS-E-210920',
 '*Training 31 ACMP Voucher Code - MIC-M365IS-E-210927',
 '*Readyness MWP Free - Reminder Email Webinar Name',
 '*Readyness MWP Free - Reminder Email Teams Link',
 '*ACMP Link (per country)',
 '*Training 37 ACMP Voucher Code - MIC-CUS-A-E-211006-1',
 '*Training 41 ACMP Voucher Code - MIC-CUS-A-E-211011',
 '*Training 42 ACMP Voucher Code - MIC-CUS-A-E-211206',
 '*Training 43 ACMP Voucher Code - MIC-CUS-A-E-211013',
 '*Training 44 ACMP Voucher Code - MIC-CUS-A-E-211208-1',
 '*Training 45 ACMP Voucher Code - MIC-CUS-A-E-211026',
 '*Training 46 ACMP Voucher Code - MIC-CUS-A-E-211015',
 '*Training 47 ACMP Voucher Code - MIC-CUS-A-E-211126-1',
 '*Training 48 ACMP Voucher Code - MIC-CUS-A-E-211210-1',
 '*Training 49 ACMP Voucher Code - MIC-PPF-E-211105',
 '*Training 50 ACMP Voucher Code - MIC-CUS-A-E-211213',
 '*Training 51 ACMP Voucher Code - MIC-CUS-A-E-211208-2',
 '*Training 52 ACMP Voucher Code - MIC-MCDA-E-211206',
 '*Training 53 ACMP Voucher Code - MIC-PPAMAKE-E-211209',
 '*Training 54 ACMP Voucher Code - DYN-365CES-E-211206',
 '*Payment Reminder Training Name',
 '*Payment Reminder Voucher Code',
 '*Email Language',
 "*Product / solution area you're interested in getting certified",
 '*Training 58 ACMP Voucher Code - MIC-CUS-A-E-211005-1',
 '*Training 59 ACMP Voucher Code - MIC-CUS-A-E-211005-2',
 '*Training 60 ACMP Voucher Code - MIC-CUS-A-E-211006-4',
 '*Training 61 ACMP Voucher Code - MIC-CUS-A-E-211006-2',
 '*Training 62 ACMP Voucher Code - MIC-CUS-A-E-211006-3',
 '*Training 63 ACMP Voucher Code - MIC-CUS-A-E-211007',
 '*Training 65 ACMP Voucher Code - MIC-CUS-A-E-211008-1',
 '*Training 66 ACMP Voucher Code - MIC-CUS-A-E-211008-2',
 '*Training 68 ACMP Voucher Code - MIC-CUS-A-E-211018',
 '*Training 69 ACMP Voucher Code - MIC-CUS-A-E-211019',
 '*Training 71 ACMP Voucher Code - MIC-CUS-A-E-211021',
 '*Training 72 ACMP Voucher Code - MIC-CUS-A-E-211022',
 '*Training 73 ACMP Voucher Code - MIC-SC300-E-211025',
 '*Training 74 ACMP Voucher Code - MIC-CUS-A-E-211028-1',
 '*Training 75 ACMP Voucher Code - MIC-CUS-A-E-211028-2',
 '*I want to receive further info on the New Commerce Experience',
 '*NCE New Commerce Experience Webinar Date',
 '*EMPM Reason to Contact',
 '*Training 77 ACMP Voucher Code - MIC-CUS-A-E-211108-1',
 '*Training 78 ACMP Voucher Code - MIC-CUS-A-E-211108-2',
 '*Training 82 ACMP Voucher Code - MIC-CUS-A-E-211110',
 '*Training 84 ACMP Voucher Code - MIC-CUS-A-E-211112-2',
 '*Training 85 ACMP Voucher Code - MIC-CUS-A-E-211116-2',
 '*Training 87 ACMP Voucher Code - MIC-AZ140-E-211122',
 '*Training 88 ACMP Voucher Code - MIC-SC300-E-211122',
 '*Training 89 ACMP Voucher Code - MIC-M365TMA-E-211123',
 '*Training 90 ACMP Voucher Code - MIC-SC200-E-211124',
 '*Training 91 ACMP Voucher Code - MIC-CUS-A-E-211126-2',
 '*Training 93 ACMP Voucher Code - MIC-SC400-E-211129',
 '*Training 94 ACMP Voucher Code - MIC-CUS-A-E-211130',
 '*Training 95 ACMP Voucher Code - MIC-CUS-A-E-211201',
 '*Training 96 ACMP Voucher Code - MIC-MCASEC-E-211201',
 '*Training 97 ACMP Voucher Code - MIC-M365SA-E-211201',
 '*Training 98 ACMP Voucher Code - MIC-M365SA-E-211202',
 '*Training 99 ACMP Voucher Code - MIC-CUS-A-E-211203-1',
 '*Training 100 ACMP Voucher Code - MIC-CUS-A-E-211203-2',
 '*Training 101 ACMP Voucher Code - MIC-MCASEC-E-211203',
 '*Training 102 ACMP Voucher Code - MIC-M365TMA-E-211207',
 '*Training 103 ACMP Voucher Code - MIC-CUS-A-E-211208-3',
 '*EXO1 Score',
 'Tags']

In [21]:
# remove all columns except the ones we need.
df_activecampaign.drop(df_activecampaign.columns.difference(['Email','Phone Number','Account (previously Organization)','*Marketing Channel']), 1, inplace=True)
df_activecampaign.head()

,Email,Phone Number,Account (previously Organization),*Marketing Channel
0,004@actum.ch,0797546618,ACTUM AG,NaN
1,010@ligbris.eu,NaN,Ligbris,NaN
2,0135223955@fpz.hr,NaN,FPZ,NaN
3,0877002284az@azgmdil.com,0877132569,Няма,NaN
4,08lond01@norrtalje.se,NaN,norrtälja.se,NaN

In [22]:
print(df_activecampaign.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20112 entries, 0 to 20111
Data columns (total 4 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Email                              20112 non-null  object
 1   Phone Number                       13561 non-null  object
 2   Account (previously Organization)  19410 non-null  object
 3   *Marketing Channel                 1086 non-null   object
dtypes: object(4)
memory usage: 628.6+ KB
None

In [23]:
# # go back to first dataframe and filter for only the tags that you need
tags_needed = ['MatureACMP: Signed Up for Ebook',
                'MatureACMP: Signed Up for Demo',
                'EmergingACMP: Signed Up for Ebook',
                'EmergingACMP: Signed Up for Demo'] 
    
# # selecting rows based on condition 
rslt_df = df_excel[df_excel['Original Tag Name'].isin(tags_needed)] 

# # check the size
rslt_df.shape[0]

864

In [24]:
# # go back to first dataframe and filter for only the tags that you need
# tags_needed = ['MTRHWWebinar: 01 Signed Up - English - November 10th',
#                'MTRHWWebinar: 01 Signed Up - German - November 9th',
#                'MTRHWWebinar: 01 Signed Up - Dutch - November 9th',
#                'MTRHWWebinar: 01 Signed Up - French - November 10th'] 
    
# # selecting rows based on condition 
# rslt_df = df_excel[df_excel['Original Tag Name'].isin(tags_needed)] 

# # check the size
# rslt_df.shape[0]

In [25]:
rslt_df.head()

,Date-Time,Date,Time,Contact ID,Country,Primary List,Contact Country,Email,Original Tag Name,First Name,Last Name,Tag Name (For Reports),Campaign Name (For Reports),Source URL,Company
51625,2022-08-30T15:19:10-05:00,30-08-2022,08:19 PM UTC,malik112+test123@gmail.com,Austria,EN,Austria,malik112+test123@gmail.com,MatureACMP: Signed Up for Ebook,Malik,test,Ebook Sign Up - Mature page,ALSO_ACMP_Partner_Recruit_IS229229,https://cloud.also.mp/mature-acmp/,NaN
51626,2022-08-30T15:19:10-05:00,30-08-2022,08:19 PM UTC,malik112+test123@gmail.com,Austria,EN,Austria,malik112+test123@gmail.com,MatureACMP: Signed Up for Demo,Malik,test,Demo Sign Up - Mature page,ALSO_ACMP_Partner_Recruit_IS229229,https://cloud.also.mp/mature-acmp/,NaN
51628,2022-08-30T15:48:23-05:00,30-08-2022,08:48 PM UTC,malik112+acmptest@gmail.com,Bulgaria,EN,Bulgaria,malik112+acmptest@gmail.com,MatureACMP: Signed Up for Demo,Malik,test,Demo Sign Up - Mature page,ALSO_ACMP_Partner_Recruit_IS229229,https://cloud.also.mp/mature-acmp/,NaN
51629,2022-08-30T15:53:35-05:00,30-08-2022,08:53 PM UTC,malik112+acmptest2@gmail.com,Bulgaria,EN,Bulgaria,malik112+acmptest2@gmail.com,MatureACMP: Signed Up for Ebook,Malik,test,Ebook Sign Up - Mature page,ALSO_ACMP_Partner_Recruit_IS229229,https://cloud.also.mp/mature-acmp/,NaN
51630,2022-08-30T15:53:35-05:00,30-08-2022,08:53 PM UTC,malik112+acmptest2@gmail.com,Bulgaria,EN,Bulgaria,malik112+acmptest2@gmail.com,MatureACMP: Signed Up for Demo,Malik,test,Demo Sign Up - Mature page,ALSO_ACMP_Partner_Recruit_IS229229,https://cloud.also.mp/mature-acmp/,NaN

In [26]:
# filter the tests
# first remove from email
rslt_df = rslt_df[~rslt_df['Email'].str.contains("test", case=False)]
# then remove from First Name
rslt_df = rslt_df[~rslt_df['First Name'].str.contains("test", case=False, na=False)]
# then remove from Last Name
rslt_df = rslt_df[~rslt_df['Last Name'].str.contains("test", case=False, na=False)]

# remove ALSO email addresses
rslt_df = rslt_df[~rslt_df['Email'].str.contains("also.com", case=False, na=False)]


# check the size
print('No of rows: ', rslt_df.shape[0])
rslt_df.head()

No of rows:  779

,Date-Time,Date,Time,Contact ID,Country,Primary List,Contact Country,Email,Original Tag Name,First Name,Last Name,Tag Name (For Reports),Campaign Name (For Reports),Source URL,Company
51682,2022-08-31T09:32:43-05:00,31-08-2022,02:32 PM UTC,sisa@zupa.dk,NaN,de/de,NaN,sisa@zupa.dk,MatureACMP: Signed Up for Ebook,Signe,Ahler,Ebook Sign Up - Mature page,ALSO_ACMP_Partner_Recruit_IS229229,https://cloud.also.mp/de/de/mature-acmp/,NaN
51875,2022-09-06T06:38:39-05:00,2022-06-09 00:00:00,11:38 AM UTC,s.hoefs@outlook.de,Deutschland,de/de,Deutschland,s.hoefs@outlook.de,MatureACMP: Signed Up for Ebook,Sabrina,Hoefs,Ebook Sign Up - Mature page,ALSO_ACMP_Partner_Recruit_IS229229,https://cloud.also.mp/de/de/mature-acmp/,Also Deutschland GmbH
51876,2022-09-06T06:41:40-05:00,2022-06-09 00:00:00,11:41 AM UTC,jessica.leuwer@gmail.com,NaN,de/de,NaN,jessica.leuwer@gmail.com,MatureACMP: Signed Up for Ebook,Jessica,Leuwer,Ebook Sign Up - Mature page,ALSO_ACMP_Partner_Recruit_IS229229,https://cloud.also.mp/de/de/mature-acmp/,ALSO
51919,2022-09-07T02:22:17-05:00,2022-07-09 00:00:00,07:22 AM UTC,nkolev@sbs.bg,NaN,bg/bg,NaN,nkolev@sbs.bg,EmergingACMP: Signed Up for Ebook,Николай,Колев,Ebook Sign Up - Emerging page,ALSO_ACMP_Partner_Recruit_IS229229,https://cloud.also.mp/bg/bg/emerging-acmp/,NaN
52008,2022-09-08T09:03:50-05:00,2022-08-09 00:00:00,02:03 PM UTC,dennis.gehrke@berenberg.com,NaN,ch/de,NaN,dennis.gehrke@berenberg.com,MatureACMP: Signed Up for Ebook,Dennis,Gehrke,Ebook Sign Up - Mature page,ALSO_ACMP_Partner_Recruit_IS229229,https://cloud.also.mp/ch/de/mature-acmp/,Berenberg

In [27]:
print(rslt_df.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 779 entries, 51682 to 55462
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Date-Time                    779 non-null    object
 1   Date                         779 non-null    object
 2   Time                         779 non-null    object
 3   Contact ID                   779 non-null    object
 4   Country                      667 non-null    object
 5   Primary List                 779 non-null    object
 6   Contact Country              667 non-null    object
 7   Email                        779 non-null    object
 8   Original Tag Name            779 non-null    object
 9   First Name                   751 non-null    object
 10  Last Name                    771 non-null    object
 11  Tag Name (For Reports)       779 non-null    object
 12  Campaign Name (For Reports)  779 non-null    object
 13  Source URL                   222 non-null    object
 14  Company                      681 non-null    object
dtypes: object(15)
memory usage: 97.4+ KB
None

In [38]:
# what we want now is a dataframe that stores the primary list and its corresponding country
# we will use the information stored in this country dataframe to update the countries that are missing.
# first - get only country and primary list and store in another dataframe
countries_df = rslt_df[['Country','Primary List']]
print(countries_df.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 779 entries, 51682 to 55462
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country       779 non-null    object
 1   Primary List  779 non-null    object
dtypes: object(2)
memory usage: 34.4+ KB
None

In [39]:
# keep updating the dataframe after removing NAs and duplicate values
countries_df = countries_df.drop_duplicates()

In [40]:
print(countries_df.reset_index(drop=True))

        Country Primary List
0       Germany        de/de
1   Deutschland        de/de
2      Bulgaria        bg/bg
3   Switzerland        ch/de
4       Schweiz        ch/de
..          ...          ...
59     Slovenia        si/si
60       Serbia        de/de
61            0        de/de
62            0        lv/lv
63    Lithuania        at/de

[64 rows x 2 columns]

In [43]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    print(countries_df)

           Country Primary List
51682      Germany        de/de
51875  Deutschland        de/de
51919     Bulgaria        bg/bg
52008  Switzerland        ch/de
52030      Schweiz        ch/de
52103     Bulgaria            0
52112      Romania            0
52119      Austria        at/de
52129       Sweden            0
52140        Spain            0
52141      Austria            0
52149       France        fr/fr
52160      Croatia        hr/hr
52221      Romania        ro/ro
52223      Romania           EN
52228       France            0
52327      Croatia            0
52358       Poland            0
52362       Poland        pl/pl
52366  Switzerland        de/de
52369  Switzerland            0
52384     Bulgaria           EN
52399       Sweden           EN
52446      Germany            0
52526       Sweden        se/se
52751        Spain        es/es
53749      Belgium        hr/hr
53874       Poland           EN
54221       Serbia        sr/sr
54336        Italy        it/it
54579      Hungary            0
54588       Serbia            0
54589       Latvia            0
54590    Lithuania            0
54591      Estonia            0
54599      Denmark            0
54602    Lithuania        lt/lt
54612        Italy            0
54613      Finland        fi/fi
54625  Netherlands        nl/nl
54645     Slovenia            0
54651      Denmark        dk/dk
54655       Norway            0
54660       Norway        no/no
54661      Estonia        ee/ee
54681      Belgium            0
54682      Belgium           EN
54693       Norway           EN
54700      Finland            0
54717       Latvia        lv/lv
54723      Denmark           EN
54745      Finland           EN
54888            0        hu/hu
54893      Germany           EN
54906            0        at/de
54911            0        si/si
54912  Netherlands            0
54963            0        fi/fi
54997            0        no/no
55125     Slovenia        si/si
55191       Serbia        de/de
55192            0        de/de
55252            0        lv/lv
55335    Lithuania        at/de

In [44]:
countries_df= countries_df[countries_df['Primary List'] != 0]
countries_df= countries_df[countries_df['Primary List'] != 'EN']

# replace duplicate names in german. have to be manually looked into
countries_df.loc[countries_df['Country'] == 'Schweiz', 'Country'] = 'Switzerland'
countries_df.loc[countries_df['Country'] == 'Deutschland', 'Country'] = 'Germany'

# since this will create duplicates, remove them
countries_df=countries_df.drop_duplicates()

# some countries (specially DACH or FR) may have incorrect combination of list. 
# this may have to be manually looked into.
countries_df = countries_df.drop(countries_df[(countries_df['Country'] == 'Switzerland') & (countries_df['Primary List'] == 'de/de')].index)

countries_df = countries_df.reset_index(drop=True)
print(countries_df)

        Country Primary List
0       Germany        de/de
1      Bulgaria        bg/bg
2   Switzerland        ch/de
3       Austria        at/de
4        France        fr/fr
5       Croatia        hr/hr
6       Romania        ro/ro
7        Poland        pl/pl
8        Sweden        se/se
9         Spain        es/es
10      Belgium        hr/hr
11       Serbia        sr/sr
12        Italy        it/it
13    Lithuania        lt/lt
14      Finland        fi/fi
15  Netherlands        nl/nl
16      Denmark        dk/dk
17       Norway        no/no
18      Estonia        ee/ee
19       Latvia        lv/lv
20            0        hu/hu
21            0        at/de
22            0        si/si
23            0        fi/fi
24            0        no/no
25     Slovenia        si/si
26       Serbia        de/de
27            0        de/de
28            0        lv/lv
29    Lithuania        at/de

In [47]:
# create only a list dataframe 
list_df = countries_df[['Primary List']]
country_only_df = countries_df[['Country']]
display(list_df)
display(country_only_df)

   Primary List
0         de/de
1         bg/bg
2         ch/de
3         at/de
4         fr/fr
5         hr/hr
6         ro/ro
7         pl/pl
8         se/se
9         es/es
10        hr/hr
11        sr/sr
12        it/it
13        lt/lt
14        fi/fi
15        nl/nl
16        dk/dk
17        no/no
18        ee/ee
19        lv/lv
20        hu/hu
21        at/de
22        si/si
23        fi/fi
24        no/no
25        si/si
26        de/de
27        de/de
28        lv/lv
29        at/de

        Country
0       Germany
1      Bulgaria
2   Switzerland
3       Austria
4        France
5       Croatia
6       Romania
7        Poland
8        Sweden
9         Spain
10      Belgium
11       Serbia
12        Italy
13    Lithuania
14      Finland
15  Netherlands
16      Denmark
17       Norway
18      Estonia
19       Latvia
20            0
21            0
22            0
23            0
24            0
25     Slovenia
26       Serbia
27            0
28            0
29    Lithuania

In [48]:
# remove duplicates from the primary list
list_df=list_df.drop_duplicates()
country_only_df=country_only_df.drop_duplicates()

display(list_df)
display(country_only_df)

   Primary List
0         de/de
1         bg/bg
2         ch/de
3         at/de
4         fr/fr
5         hr/hr
6         ro/ro
7         pl/pl
8         se/se
9         es/es
11        sr/sr
12        it/it
13        lt/lt
14        fi/fi
15        nl/nl
16        dk/dk
17        no/no
18        ee/ee
19        lv/lv
20        hu/hu
22        si/si

        Country
0       Germany
1      Bulgaria
2   Switzerland
3       Austria
4        France
5       Croatia
6       Romania
7        Poland
8        Sweden
9         Spain
10      Belgium
11       Serbia
12        Italy
13    Lithuania
14      Finland
15  Netherlands
16      Denmark
17       Norway
18      Estonia
19       Latvia
20            0
25     Slovenia

In [33]:
# replace incorrect values (if any) with the correct ones using dataframe.at[index,'column-name']='new value'

countries_df.at[10,'Primary List'] = 'be/be'
countries_df.at[21,'Primary List'] = 'sr/sr'
countries_df.at[22,'Primary List'] = 'lt/lt'
print(countries_df)

        Country Primary List
0       Germany        de/de
1   Switzerland        ch/de
2       Austria        at/de
3      Bulgaria        bg/bg
4        France        fr/fr
5       Croatia        hr/hr
6       Romania        ro/ro
7        Poland        pl/pl
8        Sweden        se/se
9         Spain        es/es
10      Belgium        be/be
11    Lithuania        lt/lt
12      Finland        fi/fi
13  Netherlands        nl/nl
14       Serbia        sr/sr
15      Denmark        dk/dk
16       Norway        no/no
17      Estonia        ee/ee
18       Latvia        lv/lv
19        Italy        it/it
20     Slovenia        si/si
21       Serbia        sr/sr
22    Lithuania        lt/lt

In [34]:
# since this will create duplicates, remove them
countries_df=countries_df.drop_duplicates()
countries_df = countries_df.reset_index(drop=True)
print(countries_df)

        Country Primary List
0       Germany        de/de
1   Switzerland        ch/de
2       Austria        at/de
3      Bulgaria        bg/bg
4        France        fr/fr
5       Croatia        hr/hr
6       Romania        ro/ro
7        Poland        pl/pl
8        Sweden        se/se
9         Spain        es/es
10      Belgium        be/be
11    Lithuania        lt/lt
12      Finland        fi/fi
13  Netherlands        nl/nl
14       Serbia        sr/sr
15      Denmark        dk/dk
16       Norway        no/no
17      Estonia        ee/ee
18       Latvia        lv/lv
19        Italy        it/it
20     Slovenia        si/si

In [49]:
# country_dict = dict (zip(countries_df['Primary List'], countries_df['Country']))
# print(country_dict)

# creating static dictionary
country_dict = {
    'de/de': 'Germany', 
    'ch/de': 'Switzerland', 
    'at/de': 'Austria', 
    'bg/bg': 'Bulgaria', 
    'fr/fr': 'France', 
    'hr/hr': 'Croatia', 
    'ro/ro': 'Romania', 
    'pl/pl': 'Poland', 
    'se/se': 'Sweden', 
    'es/es': 'Spain', 
    'be/be': 'Belgium', 
    'lt/lt': 'Lithuania', 
    'fi/fi': 'Finland', 
    'nl/nl': 'Netherlands', 
    'sr/sr': 'Serbia', 
    'dk/dk': 'Denmark', 
    'no/no': 'Norway', 
    'ee/ee': 'Estonia', 
    'lv/lv': 'Latvia', 
    'it/it': 'Italy', 
    'si/si': 'Slovenia',
        'hu/hu': 'Hungary'
}
print(country_dict)

{'de/de': 'Germany', 'ch/de': 'Switzerland', 'at/de': 'Austria', 'bg/bg': 'Bulgaria', 'fr/fr': 'France', 'hr/hr': 'Croatia', 'ro/ro': 'Romania', 'pl/pl': 'Poland', 'se/se': 'Sweden', 'es/es': 'Spain', 'be/be': 'Belgium', 'lt/lt': 'Lithuania', 'fi/fi': 'Finland', 'nl/nl': 'Netherlands', 'sr/sr': 'Serbia', 'dk/dk': 'Denmark', 'no/no': 'Norway', 'ee/ee': 'Estonia', 'lv/lv': 'Latvia', 'it/it': 'Italy', 'si/si': 'Slovenia', 'hu/hu': 'Hungary'}

In [50]:
rslt_df['Country'] = rslt_df['Country'].fillna(0)
rslt_df.head()

,Date-Time,Date,Time,Contact ID,Country,Primary List,Contact Country,Email,Original Tag Name,First Name,Last Name,Tag Name (For Reports),Campaign Name (For Reports),Source URL,Company
51682,2022-08-31T09:32:43-05:00,31-08-2022,02:32 PM UTC,sisa@zupa.dk,Germany,de/de,NaN,sisa@zupa.dk,MatureACMP: Signed Up for Ebook,Signe,Ahler,Ebook Sign Up - Mature page,ALSO_ACMP_Partner_Recruit_IS229229,https://cloud.also.mp/de/de/mature-acmp/,NaN
51875,2022-09-06T06:38:39-05:00,2022-06-09 00:00:00,11:38 AM UTC,s.hoefs@outlook.de,Deutschland,de/de,Deutschland,s.hoefs@outlook.de,MatureACMP: Signed Up for Ebook,Sabrina,Hoefs,Ebook Sign Up - Mature page,ALSO_ACMP_Partner_Recruit_IS229229,https://cloud.also.mp/de/de/mature-acmp/,Also Deutschland GmbH
51876,2022-09-06T06:41:40-05:00,2022-06-09 00:00:00,11:41 AM UTC,jessica.leuwer@gmail.com,Germany,de/de,NaN,jessica.leuwer@gmail.com,MatureACMP: Signed Up for Ebook,Jessica,Leuwer,Ebook Sign Up - Mature page,ALSO_ACMP_Partner_Recruit_IS229229,https://cloud.also.mp/de/de/mature-acmp/,ALSO
51919,2022-09-07T02:22:17-05:00,2022-07-09 00:00:00,07:22 AM UTC,nkolev@sbs.bg,Bulgaria,bg/bg,NaN,nkolev@sbs.bg,EmergingACMP: Signed Up for Ebook,Николай,Колев,Ebook Sign Up - Emerging page,ALSO_ACMP_Partner_Recruit_IS229229,https://cloud.also.mp/bg/bg/emerging-acmp/,NaN
52008,2022-09-08T09:03:50-05:00,2022-08-09 00:00:00,02:03 PM UTC,dennis.gehrke@berenberg.com,Switzerland,ch/de,NaN,dennis.gehrke@berenberg.com,MatureACMP: Signed Up for Ebook,Dennis,Gehrke,Ebook Sign Up - Mature page,ALSO_ACMP_Partner_Recruit_IS229229,https://cloud.also.mp/ch/de/mature-acmp/,Berenberg

In [51]:
for i in rslt_df.index:
    if rslt_df['Country'][i] == 0:
        rslt_df['Country'][i] = country_dict[rslt_df['Primary List'][i]]
    else:
        rslt_df['Country'][i] = rslt_df['Country'][i]

rslt_df.head()

,Date-Time,Date,Time,Contact ID,Country,Primary List,Contact Country,Email,Original Tag Name,First Name,Last Name,Tag Name (For Reports),Campaign Name (For Reports),Source URL,Company
51682,2022-08-31T09:32:43-05:00,31-08-2022,02:32 PM UTC,sisa@zupa.dk,Germany,de/de,NaN,sisa@zupa.dk,MatureACMP: Signed Up for Ebook,Signe,Ahler,Ebook Sign Up - Mature page,ALSO_ACMP_Partner_Recruit_IS229229,https://cloud.also.mp/de/de/mature-acmp/,NaN
51875,2022-09-06T06:38:39-05:00,2022-06-09 00:00:00,11:38 AM UTC,s.hoefs@outlook.de,Deutschland,de/de,Deutschland,s.hoefs@outlook.de,MatureACMP: Signed Up for Ebook,Sabrina,Hoefs,Ebook Sign Up - Mature page,ALSO_ACMP_Partner_Recruit_IS229229,https://cloud.also.mp/de/de/mature-acmp/,Also Deutschland GmbH
51876,2022-09-06T06:41:40-05:00,2022-06-09 00:00:00,11:41 AM UTC,jessica.leuwer@gmail.com,Germany,de/de,NaN,jessica.leuwer@gmail.com,MatureACMP: Signed Up for Ebook,Jessica,Leuwer,Ebook Sign Up - Mature page,ALSO_ACMP_Partner_Recruit_IS229229,https://cloud.also.mp/de/de/mature-acmp/,ALSO
51919,2022-09-07T02:22:17-05:00,2022-07-09 00:00:00,07:22 AM UTC,nkolev@sbs.bg,Bulgaria,bg/bg,NaN,nkolev@sbs.bg,EmergingACMP: Signed Up for Ebook,Николай,Колев,Ebook Sign Up - Emerging page,ALSO_ACMP_Partner_Recruit_IS229229,https://cloud.also.mp/bg/bg/emerging-acmp/,NaN
52008,2022-09-08T09:03:50-05:00,2022-08-09 00:00:00,02:03 PM UTC,dennis.gehrke@berenberg.com,Switzerland,ch/de,NaN,dennis.gehrke@berenberg.com,MatureACMP: Signed Up for Ebook,Dennis,Gehrke,Ebook Sign Up - Mature page,ALSO_ACMP_Partner_Recruit_IS229229,https://cloud.also.mp/ch/de/mature-acmp/,Berenberg

In [52]:
# get only the country column to analyze consistency
country_only = rslt_df['Country']
# remove duplicates
country_only = country_only.drop_duplicates()
country_only

51682        Germany
51875    Deutschland
51919       Bulgaria
52008    Switzerland
52030        Schweiz
52112        Romania
52119        Austria
52129         Sweden
52140          Spain
52149         France
52160        Croatia
52358         Poland
53749        Belgium
54221         Serbia
54336          Italy
54579        Hungary
54589         Latvia
54590      Lithuania
54591        Estonia
54599        Denmark
54613        Finland
54625    Netherlands
54645       Slovenia
54655         Norway
Name: Country, dtype: object

In [53]:
# there is Switzerland and Germany in German. Change that to English
rslt_df.loc[rslt_df['Country'] == 'Schweiz', 'Country'] = 'Switzerland'
rslt_df.loc[rslt_df['Country'] == 'Deutschland', 'Country'] = 'Germany'

In [54]:
rslt_df.shape[0]

779

In [55]:
# join rslt_df with our marketing channel dataframe
rslt_df_final = rslt_df.merge(df_activecampaign, on='Email', how='left')

# rename the marketing channel columns
rslt_df_final = rslt_df_final.rename(columns={"*Marketing Channel": "Marketing Channel", "Account (previously Organization)":"Company Name"})
rslt_df_final.head()

,Date-Time,Date,Time,Contact ID,Country,Primary List,Contact Country,Email,Original Tag Name,First Name,Last Name,Tag Name (For Reports),Campaign Name (For Reports),Source URL,Company,Phone Number,Company Name,Marketing Channel
0,2022-08-31T09:32:43-05:00,31-08-2022,02:32 PM UTC,sisa@zupa.dk,Germany,de/de,NaN,sisa@zupa.dk,MatureACMP: Signed Up for Ebook,Signe,Ahler,Ebook Sign Up - Mature page,ALSO_ACMP_Partner_Recruit_IS229229,https://cloud.also.mp/de/de/mature-acmp/,NaN,NaN,zupa,NaN
1,2022-09-06T06:38:39-05:00,2022-06-09 00:00:00,11:38 AM UTC,s.hoefs@outlook.de,Germany,de/de,Deutschland,s.hoefs@outlook.de,MatureACMP: Signed Up for Ebook,Sabrina,Hoefs,Ebook Sign Up - Mature page,ALSO_ACMP_Partner_Recruit_IS229229,https://cloud.also.mp/de/de/mature-acmp/,Also Deutschland GmbH,02921990,ALSO Deutschland GmbH,NaN
2,2022-09-06T06:41:40-05:00,2022-06-09 00:00:00,11:41 AM UTC,jessica.leuwer@gmail.com,Germany,de/de,NaN,jessica.leuwer@gmail.com,MatureACMP: Signed Up for Ebook,Jessica,Leuwer,Ebook Sign Up - Mature page,ALSO_ACMP_Partner_Recruit_IS229229,https://cloud.also.mp/de/de/mature-acmp/,ALSO,NaN,ALSO,NaN
3,2022-09-07T02:22:17-05:00,2022-07-09 00:00:00,07:22 AM UTC,nkolev@sbs.bg,Bulgaria,bg/bg,NaN,nkolev@sbs.bg,EmergingACMP: Signed Up for Ebook,Николай,Колев,Ebook Sign Up - Emerging page,ALSO_ACMP_Partner_Recruit_IS229229,https://cloud.also.mp/bg/bg/emerging-acmp/,NaN,NaN,Специализирани бизнес системи АД,NaN
4,2022-09-08T09:03:50-05:00,2022-08-09 00:00:00,02:03 PM UTC,dennis.gehrke@berenberg.com,Switzerland,ch/de,NaN,dennis.gehrke@berenberg.com,MatureACMP: Signed Up for Ebook,Dennis,Gehrke,Ebook Sign Up - Mature page,ALSO_ACMP_Partner_Recruit_IS229229,https://cloud.also.mp/ch/de/mature-acmp/,Berenberg,NaN,Berenberg,NaN

In [56]:
# drop everything except the columns that are needed
cols_needed = ['Date-Time',
               'Email',
               'First Name', 
               'Last Name', 
               'Phone Number',
               'Tag Name (For Reports)',
               'Company Name',
               'Country', 
               'Marketing Channel']

# create a final dataframe with only these columns
leads_list = rslt_df_final[cols_needed]
print(leads_list.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 779 entries, 0 to 778
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Date-Time               779 non-null    object
 1   Email                   779 non-null    object
 2   First Name              751 non-null    object
 3   Last Name               771 non-null    object
 4   Phone Number            266 non-null    object
 5   Tag Name (For Reports)  779 non-null    object
 6   Company Name            732 non-null    object
 7   Country                 779 non-null    object
 8   Marketing Channel       643 non-null    object
dtypes: object(9)
memory usage: 60.9+ KB
None

In [57]:
# then remove if company name contains ALSO
leads_list = leads_list[~leads_list['Company Name'].str.contains("ALSO", case=False, na=False)]

In [58]:
# loop for marketing channels wherever null - add web
leads_list['Marketing Channel'] = leads_list['Marketing Channel'].fillna(0)
for i in leads_list.index:
    if leads_list['Marketing Channel'][i] == 0:
        leads_list['Marketing Channel'][i] = 'Web'
    else:
        leads_list['Marketing Channel'][i] = leads_list['Marketing Channel'][i]

leads_list.head()

,Date-Time,Email,First Name,Last Name,Phone Number,Tag Name (For Reports),Company Name,Country,Marketing Channel
0,2022-08-31T09:32:43-05:00,sisa@zupa.dk,Signe,Ahler,NaN,Ebook Sign Up - Mature page,zupa,Germany,Web
3,2022-09-07T02:22:17-05:00,nkolev@sbs.bg,Николай,Колев,NaN,Ebook Sign Up - Emerging page,Специализирани бизнес системи АД,Bulgaria,Web
4,2022-09-08T09:03:50-05:00,dennis.gehrke@berenberg.com,Dennis,Gehrke,NaN,Ebook Sign Up - Mature page,Berenberg,Switzerland,Web
5,2022-09-09T02:45:25-05:00,philipp.imstepf@ocom.ch,Philipp,Imstepf,NaN,Ebook Sign Up - Mature page,NaN,Switzerland,Web
6,2022-09-12T06:58:21-05:00,galinakatsarska@gmail.com,Галина,Кацарска,NaN,Ebook Sign Up - Mature page,HR consultant,Bulgaria,Facebook

In [59]:
leads_list.shape[0]

774

In [60]:
leads_list.to_excel("acmp_recruit_23nov.xlsx")